sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
  - oraclejdk8
install: true
script:
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || ./mvnw -pl spring-cloud-dataflow-core cobertura:cobertura package -Pfull -U -Dmaven.test.redirectTestOutputToFile=true'
  - '[ "${TRAVIS_PULL_REQUEST}"  = "false" ] || ./mvnw -pl spring-cloud-dataflow-core cobertura:cobertura package -Pfull -U -Dmaven.test.redirectTestOutputToFile=true'

after_success:
  - bash <(curl -s https://codecov.io/bash)
